[package]
name = "tfm-plugin-rust"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.97"

[lib]
crate-type = ["cdylib"]

[dependencies]
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
syn = { version = "2.0.119", features = ["full", "visit", "extra-traits"] }
wit-bindgen = { version = "=0.60.0", features = ["async"] }
